name: prepare-ios-build
description: Action to prepare environment for ios build

runs:
  using: composite
  steps:
    - name: ci/install-os-deps
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
      shell: bash
      run: |
        echo "::group::install-os-deps"
        brew install --overwrite python@3.12
        rm '/usr/local/bin/2to3-3.11'
        brew unlink python@3.11 || true
        brew link --overwrite python@3.11
        brew install watchman
        echo "::endgroup::"

    - name: Cache Homebrew
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ~/Library/Caches/Homebrew
        key: ${{ runner.os }}-homebrew-${{ hashFiles('**/Brewfile') }}
        restore-keys: |
          ${{ runner.os }}-homebrew-

    - name: ci/prepare-mobile-build
      uses: ./.github/actions/prepare-mobile-build

    - name: ci/install-pods-dependencies
      shell: bash
      run: |
        echo "::group::install-pods-dependencies"
        npm run ios-gems
        npm run pod-install
        echo "::endgroup::"

    - name: Cache Pods
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
