name: prepare-ios-build
description: Action to prepare environment for ios build

runs:
  using: composite
  steps:
    - name: ci/install-os-deps
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
      shell: bash
      run: |
        echo "::group::install-os-deps"
        brew install --overwrite python@3.12
        rm '/usr/local/bin/2to3-3.11'
        brew link --overwrite python@3.11
        brew install watchman
        echo "::endgroup::"

    - name: ci/prepare-mobile-build
      uses: ./.github/actions/prepare-mobile-build

    - name: ci/install-pods-dependencies
      shell: bash
      run: |
        echo "::group::install-pods-dependencies"
        npm run ios-gems
        npm run pod-install
        echo "::endgroup::"
