name: prepare-mobile-build
description: Action to prepare environment for mobile build

runs:
  using: composite
  steps:
    - name: Install Ruby 2.7.7 (self-hosted)
      if: ${{ runner.os == 'macOS' && runner.osVersion == '13' }}
      shell: bash
      run: |
        brew install rbenv
        rbenv install 2.7.7
        rbenv global 2.7.7
        echo "::add-path::$(rbenv root)/shims"

    # Use ruby/setup-ruby for supported macOS images
    - name: Install Ruby 2.7.7 (supported images)
      if: ${{ runner.os == 'macOS' && runner.osVersion != '13' }}
      shell: bash
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.7

    - name: ci/setup-fastlane-dependencies
      shell: bash
      run: |
        echo "::group::setup-fastlane-dependencies"
        bundle install
        echo "::endgroup::"
      working-directory: ./fastlane

    - name: ci/prepare-node-deps
      uses: ./.github/actions/prepare-node-deps
