name: prepare-mobile-build
description: Action to prepare environment for mobile build

runs:
  using: composite
  steps:
    - name: Install Ruby using ruby-build
      run: |
        # Install rbenv and ruby-build if not already installed
        if [ ! -d "$HOME/.rbenv" ]; then
          git clone https://github.com/rbenv/rbenv.git $HOME/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $HOME/.bash_profile
          echo 'eval "$(rbenv init -)"' >> $HOME/.bash_profile
          source $HOME/.bash_profile
        fi

        if [ ! -d "$HOME/.rbenv/plugins/ruby-build" ]; then
          git clone https://github.com/rbenv/ruby-build.git $HOME/.rbenv/plugins/ruby-build
        fi

        # Install Ruby 2.7.7
        rbenv install 2.7.7

        # Mark Ruby installation as complete
        touch $RUNNER_TOOL_CACHE/Ruby/2.7.7/arm64.complete

    - name: ci/setup-fastlane-dependencies
      shell: bash
      run: |
        echo "::group::setup-fastlane-dependencies"
        bundle install
        echo "::endgroup::"
      working-directory: ./fastlane

    - name: ci/prepare-node-deps
      uses: ./.github/actions/prepare-node-deps
