name: Detox E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'auto'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6

      - name: Install Dependencies
        run: |
          npm -g install react-native-cli
          brew install watchman
          brew install gnupg
          brew tap wix/brew
          brew install applesimutils
          npm install

      - name: Configure Xcode Preferences
        run: |
          # Set Xcode's build location
          mkdir -p ~/Library/Developer/Xcode/DerivedData
          defaults write com.apple.dt.Xcode IDECustomDerivedDataLocation -string YES
          defaults write com.apple.dt.Xcode CustomDerivedDataLocation -string "build"
          defaults write com.apple.dt.Xcode CustomDerivedDataLocationType -string 3
  
      - name: Build iOS app
        run: npm run build:ios-sim

      - name: Start Server
        run: npm run start &

      - name: Install Detox Dependencies
        run: cd detox && npm install

      - name: Run Detox Tests
        run: npm run e2e:ios
