name: Detox E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-ios:
    runs-on: macos-13-xlarge
    steps:

      - name: ci/checkout-repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: ci/install-os-deps
        env:
          HOMEBREW_NO_AUTO_UPDATE: "1"
        shell: bash
        run: |
          echo "::group::install-os-deps"
          brew tap wix/brew
          brew install applesimutils
          brew install watchman
          echo "::endgroup::"

      # Install Ruby 2.7.7 on self-hosted macOS-13-arm64 runners
      - name: Install Ruby 2.7.7 (self-hosted)
        if: ${{ runner.os == 'macOS' && runner.osVersion == '13' }}
        run: |
          brew install rbenv
          rbenv install 2.7.7
          rbenv global 2.7.7
          echo "::add-path::$(rbenv root)/shims"

      # Use ruby/setup-ruby for supported macOS images
      - name: Install Ruby 2.7.7 (supported images)
        if: ${{ runner.os == 'macOS' && runner.osVersion != '13' }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.7

      - name: ci/setup-fastlane-dependencies
        shell: bash
        run: |
          echo "::group::setup-fastlane-dependencies"
          bundle install
          echo "::endgroup::"
          working-directory: ./fastlane
    
      - name: ci/prepare-node-deps
        uses: ./.github/actions/prepare-node-deps

      - name: ci/build-ios-simulator
        env:
          TAG: "${{ github.ref_name }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.MM_MOBILE_BETA_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.MM_MOBILE_BETA_AWS_SECRET_ACCESS_KEY }}"
          MATTERMOST_WEBHOOK_URL: "${{ secrets.MM_MOBILE_BETA_MATTERMOST_WEBHOOK_URL }}"
          GITHUB_TOKEN: "${{ secrets.MM_MOBILE_GITHUB_TOKEN }}"
        run: bundle exec fastlane ios simulator --env ios.simulator
        working-directory: ./fastlane

      - name: ci/upload-ios-pr-simulator
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-simulator-${{ github.run_id }}
          path: Mattermost-simulator-x86_64.app.zip

      - name: Download iOS build artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-build-simulator-${{ github.run_id }}
          path: mobile-artifacts

      - name: Unzip artifact
        run: unzip -o mobile-artifacts/*.zip -d mobile-artifacts/

      - name: Run react-native
        run: npm run start &

      - name: Install detox dependancies
        run: |
          ls -l mobile-artifacts/
          cd detox && npm install
      - name: Run detox e2e
        run: npm run e2e:ios
