name: Detox E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.actions.callWithGitHubToken(
              { owner: context.repo.owner, repo: context.repo.repo },
              'workflow_dispatch',
              {
                workflow: 'build-pr.yml'
              }
            )

  e2e-ios:
    needs: trigger_build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: ios-build-pr-${{ github.run_id }}
          path: mobile-artifacts

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .node-version

      - name: Install Detox dependencies
        run: |
          gem install detox-instruments detox-android
          cd ios && pod install

      - name: Download iOS build artifact
        uses: actions/download-artifact@v2
        with:
          name: ios-build-pr-${{ github.run_id }}
          path: mobile-artifacts

      - name: Unzip artifact (if necessary)
        run: |
          if [[ $OSTYPE == 'darwin' ]]; then
            unzip mobile-artifacts/*.zip
          else
            unzip -o mobile-artifacts/*.zip
          fi

      - name: Run Detox tests (iOS)
        run: npx detox run-all --test=e2e --configuration ios --platform ios --artifacts-dir mobile-artifacts

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: detox-results
          path: ios/reports
  