name: Detox E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - add_e2e_CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  generate-specs:
    runs-on: ubuntu-22.04
    outputs:
      specs: ${{ steps.generate-specs.outputs.specs }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Test Specs
        id: generate-specs
        uses: ./.github/actions/generate-specs
        with:
          parallelism: 10
          directory: detox/e2e
          search_path: test

  build-ios-simulator:
    runs-on: macos-14-large
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare iOS Build
        uses: ./.github/actions/prepare-ios-build

      - name: Build iOS Simulator
        env:
          TAG: "${{ github.ref_name }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.MM_MOBILE_BETA_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.MM_MOBILE_BETA_AWS_SECRET_ACCESS_KEY }}"
          GITHUB_TOKEN: "${{ secrets.MM_MOBILE_GITHUB_TOKEN }}"
        run: bundle exec fastlane ios simulator --env ios.simulator || true
        working-directory: ./fastlane

      - name: Upload iOS Simulator Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-simulator-${{ github.run_id }}
          path: Mattermost-simulator-x86_64.app.zip

  e2e-ios:
    env:
      IOS: true
    runs-on: macos-14-large
    name: test-detox-e2e-${{ matrix.runId }}
    needs:
      - generate-specs
      - build-ios-simulator
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-specs.outputs.specs) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Homebrew Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Download iOS Simulator Build
        uses: actions/download-artifact@v4
        with:
          name: ios-build-simulator-${{ github.run_id }}
          path: mobile-artifacts

      - name: Unzip iOS Simulator Build
        run: unzip -o mobile-artifacts/*.zip -d mobile-artifacts/

      - name: Start React Native Metro Server
        run: npm run start &

      - name: Install Detox Dependencies
        run: cd detox && npm ci

      - name: Run Detox E2E Tests
        run: cd detox && npm run e2e:ios-test -- ${{ matrix.specs }}

      - name: Upload iOS Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-results-${{ matrix.runId }}
          path: detox/artifacts/

  build-android-apk:
    runs-on: macos-14-large
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: ci/prepare-android-build
        uses: ./.github/actions/prepare-android-build
        env:
          STORE_FILE: "${{ secrets.MM_MOBILE_STORE_FILE }}"
          STORE_ALIAS: "${{ secrets.MM_MOBILE_STORE_ALIAS }}"
          STORE_PASSWORD: "${{ secrets.MM_MOBILE_STORE_PASSWORD }}"
          MATTERMOST_BUILD_GH_TOKEN: "${{ secrets.MATTERMOST_BUILD_GH_TOKEN }}"

      - name: Install Detox dependencies
        run: cd detox && npm ci

      - name: Build android apk
        run: |
          cd detox
          npm run e2e:android-build

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-build-apk-${{ github.run_id }}
          path: android/app/build/outputs/apk/debug/app-debug.apk

  e2e-android:
    env:
      IOS: false
    runs-on: macos-14-large
    name: test-detox-e2e-${{ matrix.runId }}
    needs:
      - generate-specs
      - build-android-apk
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-specs.outputs.specs) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-build-apk-${{ github.run_id }}
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Start React Native Metro Server
        run: npm run start &

      - name: Install Detox Dependencies
        run: cd detox && npm ci

      - name: Run Detox E2E Tests
        run: cd detox && npm run e2e:ios-test -- ${{ matrix.specs }}

      - name: Upload iOS Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-results-${{ matrix.runId }}
          path: detox/artifacts

  download-e2e-results:
    runs-on: ubuntu-22.04
    if: always()
    needs:
      - generate-specs
      - e2e-ios
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download iOS E2E Test Results
        uses: actions/download-artifact@v4
        with:
          name: ios-results-${{ needs.e2e-ios.outputs.matrix.runId }}
          path: detox/artifacts/

      - name: Save report Detox Dependencies
        run: cd detox && npm run e2e:save-report
