name: Detox E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .node-version

      - name: Configure Xcode Preferences
        run: |
          # Set Xcode's build location
          mkdir -p ~/Library/Developer/Xcode/DerivedData
          defaults write com.apple.dt.Xcode IDECustomDerivedDataLocation -string YES
          defaults write com.apple.dt.Xcode CustomDerivedDataLocation -string "build"
          defaults write com.apple.dt.Xcode CustomDerivedDataLocationType -string 3

      - name: Install macOS dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
          brew install watchman
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7.6

      - name: Cache CocoaPods
        id: cache-cocoapods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install npm dependencies
        run: npm install --ignore-scripts

      - name: Install iOS dependencies
        run: |
          gem install cocoapods -v 1.14.3
          npm run ios-gems
          # npm run pod-install

      - name: Install detox node dependencies
        run: cd detox && npm install && cd ..

      - name: Detox rebuild framework cache
        run: npx detox rebuild-framework-cache

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: ios/build
          key: ${{ runner.os }}-detox-build
          restore-keys: |
            ${{ runner.os }}-detox-build

      - name: Run server
        run: npm run start

      - name: Detox build
        run: npm run build:ios-sim

      - name: Detox test
        run: npm run e2e:ios

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts
  