name: Detox E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  BRANCH: ${{ github.head_ref || github.ref_name }} 
  BUILD_ID: ${{ github.run_id }}
  COMMIT_HASH: ${{ github.sha }}
  AWS_REGION: 'us-east-1'
  DETOX_AWS_S3_BUCKET: 'mattermost-detox-report'
  DETOX_AWS_ACCESS_KEY_ID: ${{ secrets.MM_MOBILE_DETOX_AWS_ACCESS_KEY_ID }}
  DETOX_AWS_SECRET_ACCESS_KEY: ${{ secrets.MM_MOBILE_DETOX_AWS_SECRET_ACCESS_KEY }}
  HEADLESS: 'false'
  TYPE: 'PR'
  PULL_REQUEST: 'https://github.com/mattermost/mattermost-mobile/pull/${{ github.event.number }}'
  ZEPHYR_ENABLE: false
  JIRA_PROJECT_KEY: 'MM'
  ZEPHYR_API_KEY: ${{ secrets.MM_MOBILE_E2E_ZEPHYR_API_KEY }}
  ZEPHYR_FOLDER_ID: '3233873'
  TEST_CYCLE_LINK_PREFIX: ${{ secrets.MM_MOBILE_E2E_TEST_CYCLE_LINK_PREFIX }}
  WEBHOOK_URL: ${{ secrets.MM_MOBILE_E2E_WEBHOOK_URL }}
  FAILURE_MESSAGE: "Something has failed"
  
jobs:
  generate-specs:
    runs-on: ubuntu-22.04
    if: (contains(github.event.pull_request.labels.*.name, 'E2E iOS tests for PR') || contains(github.event.pull_request.labels.*.name, 'E2E Android tests for PR'))
    outputs:
      specs: ${{ steps.generate-specs.outputs.specs }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Generate Test Specs
        id: generate-specs
        uses: ./.github/actions/generate-specs
        with:
          parallelism: 10
          directory: detox/e2e
          search_path: test
          device: iPhone 15 Pro
          os_version: 17.4

  # build-ios-simulator:
  #   runs-on: macos-14-large
  #   if: contains(github.event.pull_request.labels.*.name, 'E2E iOS tests for PR')
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

  #     - name: Prepare iOS Build
  #       uses: ./.github/actions/prepare-ios-build

  #     - name: Build iOS Simulator
  #       env:
  #         TAG: "${{ github.ref_name }}"
  #         AWS_ACCESS_KEY_ID: "${{ secrets.MM_MOBILE_BETA_AWS_ACCESS_KEY_ID }}"
  #         AWS_SECRET_ACCESS_KEY: "${{ secrets.MM_MOBILE_BETA_AWS_SECRET_ACCESS_KEY }}"
  #         GITHUB_TOKEN: "${{ secrets.MM_MOBILE_GITHUB_TOKEN }}"
  #       run: bundle exec fastlane ios simulator --env ios.simulator
  #       working-directory: ./fastlane

  #     - name: Upload iOS Simulator Build
  #       uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
  #       with:
  #         name: ios-build-simulator-${{ github.run_id }}
  #         path: Mattermost-simulator-x86_64.app.zip

  e2e-ios:
    env:
      IOS: true
    runs-on: macos-14-large
    name: ios-detox-e2e-${{ matrix.runId }}-${{ matrix.device }}-${{ matrix.os }}
    if: contains(github.event.pull_request.labels.*.name, 'E2E iOS tests for PR')
    needs:
      - generate-specs
      # - build-ios-simulator
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-specs.outputs.specs) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: ci/prepare-node-deps
        uses: ./.github/actions/prepare-node-deps
  
      - name: Set Build ID
        run: |
          DEVICE_NAME=$(node -p "require('./.detoxrc').devices['ios.simulator'].device.type")
          DEVICE_OS_VERSION=$(node -p "require('./.detoxrc').devices['ios.simulator'].device.os")
          echo "BUILD_ID=${{ github.run_id }}-${{ matrix.device }}-${{ matrix.os }}" >> $GITHUB_ENV
          echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV
          echo "DEVICE_OS_VERSION=$DEVICE_OS_VERSION" >> $GITHUB_ENV

      - name: Test step
        run: echo ${{ fromJSON(needs.generate-specs.outputs.specs) }}
  
  #     - name: Install Homebrew Dependencies
  #       run: |
  #         brew tap wix/brew
  #         brew install applesimutils

  #     - name: Download iOS Simulator Build
  #       uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
  #       with:
  #         name: ios-build-simulator-${{ github.run_id }}
  #         path: mobile-artifacts

  #     - name: Unzip iOS Simulator Build
  #       run: unzip -o mobile-artifacts/*.zip -d mobile-artifacts/

  #     - name: Start React Native Metro Server
  #       run: npm run start &

  #     - name: Install Detox Dependencies
  #       run: cd detox && npm i

  #     - name: Run Detox E2E Tests
  #       run: cd detox && npm run e2e:ios-test -- ${{ matrix.specs }}

  #     - name: Upload iOS Test Report
  #       if: always()
  #       uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
  #       with:
  #         name: ios-results-${{ matrix.runId }}
  #         path: detox/artifacts/

  # download-e2e-results:
  #   runs-on: ubuntu-22.04
  #   if: always() && (contains(github.event.pull_request.labels.*.name, 'E2E iOS tests for PR') || contains(github.event.pull_request.labels.*.name, 'E2E Android tests for PR'))
  #   needs:
  #     - generate-specs
  #     - e2e-ios
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
  
  #     - name: ci/prepare-node-deps
  #       uses: ./.github/actions/prepare-node-deps
  
  #     - name: Create artifacts directory
  #       run: |
  #         mkdir -p detox/artifacts/

  #     - name: Download All Artifacts
  #       uses:  actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
  #       with:
  #         path: detox/artifacts/
  #         pattern: ios-results-*

  #     - name: Save report Detox Dependencies
  #       run: |
  #         cd detox
  #         npm ci
  #         npm run e2e:save-report
  #       env:
  #         IOS: true
